# Generated by Django 4.2.26 on 2026-01-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_videoads_product_location_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebanner',
            old_name='subtitle',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='loginbanner',
            old_name='subtitle',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='videoads',
            old_name='text',
            new_name='caption',
        ),
    ]
