# Generated by Django 4.2.26 on 2026-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_subtitle_homepagebanner_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoads',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
